account/urls.py
from django.urls import path

from . import views

app_name="account"

urlpatterns = [
    path('', views.homepage, name='homepage'),
    path('login/', views.loginview, name='loginpage'), 
    path('logout/', views.logout_view, name='logoutpage'),
    path('register/', views.registerview, name='registerpage'),
    path('profile/update/', views.update_profile, name='update_profile'),
    path('profile/', views.profile_detail, name='profile_detail'),
]
 

cloud_monitoring_tool/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('monitoring_app/', include('monitoring_app.urls')),
    path('', include('account.urls'))
    
   
]

monitoring_app/urls.py
from django.urls import path
from . import views

app_name='monitoring_app'

urlpatterns = [ 
   path('current-metrics/', views.retrieve_and_save_metrics, name='current_metrics'),
   path('compare-metrics/', views.compare_metrics_view, name='compare_metrics')
]

templates/global/footer.html
{% load static %}
{% block content %}

        <!-- Footer Start -->
        <div class="container-fluid pt-4 px-4">
            <div class="bg-light rounded-top p-4">
                <div class="row">
                    <div class="col-12 col-sm-6 text-center text-sm-start">
                        &copy; <a href="#">Miazee IT</a>, All Right Reserved. 
                    </div>
                    <div class="col-12 col-sm-6 text-center text-sm-end">
                        <!--/*** This template is free as long as you keep the footer author’s credit link/attribution link/backlink. If you'd like to use the template without the footer author’s credit link/attribution link/backlink, you can purchase the Credit Removal License from "https://htmlcodex.com/credit-removal". Thank you for your support. ***/-->
                        Usages <a href="#">Office Management Software</a>
                    </div>
                </div>
            </div>
        </div>
        <!-- Footer End -->

{% endblock %}

templates/global/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'account:homepage' %}"><h2 style="width:112; height:50; ">Altaf</h2></a>
      
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
       
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            {% if request.user.is_authenticated  %}
            <div class="navbar-start">
              <a href="{% url 'monitoring_app:current_metrics' %}" class="navbar-item">
                Cloud metrics
                </a>
                <a href="{% url 'monitoring_app:compare_metrics' %}" class="navbar-item">
                  Comparison
                 </a>
             </div>
            {% endif %}
          </li>
        </ul>
       
        <form class="d-flex">

          {% if request.user.is_authenticated  %}

          <a href="{% url 'account:profile_detail' %}" class="button is-light">
            Profile
          </a>
            
          <a href="{% url 'account:logoutpage' %}" class="button is-light">
            Sign out
          </a>
          {% else %}
          <a href="{% url 'account:registerpage' %}" class="button is-info">
            <strong>Sign up</strong>
          </a>
          <a href="{% url 'account:loginpage' %}" class="button is-light">
            Sign in
          </a>
          {% endif %}

        </form>
      </div>
    </div>
  </nav>